# Generated by Django 4.2.11 on 2024-05-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_id_alter_feedback_id_alter_orders_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_sale',
            field=models.BooleanField(default=False, null=True, verbose_name='Разпродажба'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, null=True, verbose_name='Нов'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Нова', 'Нова'), ('Приета', 'Приета'), ('Обработва се', 'Обработва се'), ('Изпратена', 'Изпратена')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
    ]
