# Generated by Django 4.2.11 on 2024-05-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Нова', 'Нова'), ('Приета', 'Приета'), ('Обработва се', 'Обработва се'), ('Изпратена', 'Изпратена')], max_length=50, null=True),
        ),
    ]
